version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/usr/src/app/"
    command: npm run dev
    env_file: env/api.env
    ports: 
      - "3000:3000"